=== kramdar/litesql/src/generator/litesql.dtd
<!ELEMENT database (object|relation)+>
<!ATTLIST database
          name ID #REQUIRED
          namespace NMTOKEN #REQUIRED
	  include CDATA #IMPLIED>

<!ELEMENT type EMPTY>
<!ATTLIST type
          name NMTOKEN
          class NMTOKEN
          sql-type CDATA>

<!ELEMENT include EMPTY>
<!ATTLIST file CDATA>

<!ELEMENT object ((field)*,(method)*,(index)*)>
<!ATTLIST object
          name ID #REQUIRED
          inherits NMTOKEN #IMPLIED>

<!ELEMENT field (value)*>
<!ATTLIST field 
          name NMTOKEN #REQUIRED
          type (boolean|integer|string|float|time|date|datetime) #REQUIRED
          default CDATA #IMPLIED
          indexed (true|false) "false"
          unique (true|false) "false">

<!ELEMENT index (indexfield, (indexfield)+)>
<!ATTLIST index 
          unique (true|false) "false">
<!ELEMENT indexfield EMPTY>
<!ATTLIST indexfield
          name NMTOKEN #REQUIRED>
          
<!ELEMENT value EMPTY>
<!ATTLIST value
          name NMTOKEN #REQUIRED
          value CDATA #REQUIRED>

<!ELEMENT method (param)*>
<!ATTLIST method 
          name NMTOKEN #REQUIRED
          returntype CDATA 'void'
          const (true|false) 'false'>

<!ELEMENT param EMPTY>
<!ATTLIST param
          name NMTOKEN #REQUIRED
          type CDATA #REQUIRED>
          
<!ELEMENT relation ((relate)*,(field)*,(index)*)>
<!ATTLIST relation
          name NMTOKEN #IMPLIED
          id NMTOKEN #IMPLIED
          unidir (true|false) "false">

                   
<!ELEMENT relate EMPTY>
<!ATTLIST relate
          unique (true|false) "false"
          limit (one|many) "many"
          object IDREF #REQUIRED
          handle NMTOKEN #IMPLIED>

=== kramdar/litesql/src/examples/exampledatabase.xml
<?xml version="1.0"?>
<!DOCTYPE database SYSTEM "litesql.dtd"> 
<database name="ExampleDatabase" namespace="example">
  <include name="auth.xml" />
    <object name="Person">
        <field name="name" type="string"/>
        <field name="age" type="integer" default="15"/>
      <field name="image" type="blob"/>
      <field name="aDoubleValue" type="double"/>
      <field name="sex" type="integer">
            <value name="Male" value="0"/>
            <value name="Female" value="1"/>
        </field>
        <method name="sayHello"/>
      <index unique="true">
        <indexfield name="name"/>
        <indexfield name="age"/>
      </index>

    </object>
    <relation id="Mother" unidir="true">
        <relate object="Person" limit="many" handle="mother"/>
        <relate object="Person" limit="one"/>
    </relation>
    <relation id="Father" unidir="true">
        <relate object="Person" limit="many" handle="father"/>
        <relate object="Person" limit="one"/>
    </relation>
    <relation id="Siblings">
        <relate object="Person" handle="siblings"/>
        <relate object="Person"/>
    </relation>
    <relation id="Children" unidir="true">
        <relate object="Person" handle="children"/>
        <relate object="Person"/>
    </relation>
    <object name="Role"/>
    <object name="Student" inherits="Role"/>
    <object name="Employee" inherits="Role"/>
    <relation id="Roles" name="RoleRelation">
        <relate object="Person" handle="roles" limit="one"/>
        <relate object="Role" handle="person"/>
    </relation>
    <object name="School">
        <field name="name" type="string"/>
    </object>
    <relation>
        <relate object="Student" handle="school"/>
        <relate object="School" handle="students" limit="one"/>
        
    </relation>
    <object name="Office"/>
    <relation>
        <relate object="Employee" handle="office"/>
        <relate object="Office" handle="employees"/>
    </relation>
  <object name="ThingWithMethods">
    <method name="sayHello">
      <param type="string" name="text" />
      <param type="int" name="repeat" />

    </method>  

  </object>
</database>
